name: AWS EC2 Deploy CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: excuting remote ssh commands
      uses: appleboy/ssh-action@v0.1.6 # ssh 접속하는 오픈소스
      with:
        host: ${{ secrets.REMOTE_IP }} # 인스턴스 IP
        username: ${{ secrets.REMOTE_USER }} # 우분투 아이디
        key: ${{ secrets.REMOTE_PRIVATE_KEY }} # ec2 instance pem key
        port: ${{ secrets.REMOTE_SSH_PORT }} # 접속포트
        script: | # 실행할 스크립트
          cd /home/ec2-user/test
          git pull origin main
          pm2 kill
          npm i --force
          npm run build
          pm2 start dist/main.js