name: AWS Lambda Deploy CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BUCKET: ""

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      # - name: Set up AWS CLI
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ap-northeast-2
      
      # - name: Clear all files to S3
      #   run: |
      #     aws s3 rm --recursive $BUCKET
          
      # - name: Upload all files to S3
      #   run: |
      #     aws s3 cp --recursive --exclude ".*" --exclude "README.md" . $BUCKET