name: AWS EC2 Deploy CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: excuting remote ssh commands
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.REMOTE_IP }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_PRIVATE_KEY }}
        port: ${{ secrets.REMOTE_SSH_PORT }}
        script: |
          pm2 kill
          cd /home/ec2-user
          rm -rf app
          rm -rf waterIV-Server
          git clone https://github.com/eulovehan/waterIV-Server.git
          mv waterIV-Server app
          cd app
          cp -rp /home/ec2-user/config.js ./
          npm i --force
          npm run-script build
          pm2 start dist/index.js